WITH RECURSIVE HOUR_CNT AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM HOUR_CNT
    WHERE HOUR < 23
)

SELECT HOUR_CNT.HOUR,COUNT(ANIMAL_OUTS.ANIMAL_ID) AS COUNT
FROM HOUR_CNT
LEFT JOIN ANIMAL_OUTS
ON HOUR_CNT.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY HOUR_CNT.HOUR
ORDER BY HOUR_CNT.HOUR