SELECT CITY, LENGTH(CITY)
FROM STATION
WHERE CITY = (
        SELECT CITY
        FROM STATION
        ORDER BY LENGTH(CITY) ASC, CITY
        LIMIT 1
    ) OR
    CITY = (
        SELECT CITY
        FROM STATION
        ORDER BY LENGTH(CITY) DESC, CITY
        LIMIT 1
    )
ORDER BY LENGTH(CITY)
    